services:
  nudlers-db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${NUDLERS_DB_NAME}
      POSTGRES_USER: ${NUDLERS_DB_USER}
      POSTGRES_PASSWORD: ${NUDLERS_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    command: postgres -c ssl=off
    networks:
      - nudlers-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NUDLERS_DB_USER} -d ${NUDLERS_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nudlers-app:
    build:
      context: ./app
    env_file:
      - .env
    environment:
      - NUDLERS_DB_USER=${NUDLERS_DB_USER}
      - NUDLERS_DB_HOST=nudlers-db
      - NUDLERS_DB_NAME=${NUDLERS_DB_NAME}
      - NUDLERS_DB_PASSWORD=${NUDLERS_DB_PASSWORD}
      - NUDLERS_DB_PORT=${NUDLERS_DB_PORT}
      - NUDLERS_ENCRYPTION_KEY=${NUDLERS_ENCRYPTION_KEY}
    ports:
      - "3000:3000"
    depends_on:
      nudlers-db:
        condition: service_healthy
    networks:
      - nudlers-network
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    shm_size: '2gb'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    
volumes:
  db-data:

networks:
  nudlers-network:
    driver: bridge
